=== EstibalizGutierrez/reto3Grupo6/LENGUAJES/XML/spotify.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="spotify">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="artistas">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="artista" minOccurs="1" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
<!-- Elementos de artista-->
										<xsd:element name="nombreArtistico" type="tipoPalabras"/>
										<xsd:element name="genero" type="tipoPalabras"/>
										<xsd:element name="imagen" type="tipoPalabras"/>
										<xsd:element name="descripcion" type="tipoPalabras"/>

<!-- Choice para elegir entre musico o podcaster-->
										<xsd:choice>
<!-- Opción musico-->
											<xsd:element name="musico">
												<xsd:complexType>
													<xsd:sequence>
<!-- Elemento de músico-->
														<xsd:element name="album" maxOccurs="unbounded">
															<xsd:complexType>
																<xsd:sequence>
																	<!-- Elementos de álbum-->
																	<xsd:element name="titulo" type="tipoPalabras"/>
																	<xsd:element name="anno" type="xsd:date"/>
																	<xsd:element name="genero" type="tipoPalabras"/>
																	<xsd:element name="imagen" type="tipoPalabras"/>
																	<xsd:element name="canciones">
																		<xsd:complexType>
																			<xsd:sequence>
																				<xsd:element name="cancion" maxOccurs="unbounded">
																					<xsd:complexType>
																						<xsd:sequence>
																							<!-- Elementos de canción-->
																							<xsd:element name="nombre" type="tipoPalabras"/>
<!--POSIBLE TIPO TIME-->
																							<xsd:element name="duracion" type="xsd:time"/>
																							<xsd:element name="archivo" type="tipoPalabras"/>
																							<xsd:element name="NReproducciones" type="xsd:integer"/>
																							<xsd:element name="artistasInvitados" type="tipoPalabras"/>
																						</xsd:sequence>

																					<!-- Atributo canción-->
																					<xsd:attribute name="id" type="tipoIdAudio"/>

																					</xsd:complexType>
																				</xsd:element>
																			</xsd:sequence>
																		</xsd:complexType>
																	</xsd:element>

																</xsd:sequence>
														
<!-- Atributo de álbum-->
															<xsd:attribute name="id" type="tipoIdAlbum"/>
															
															</xsd:complexType>
														</xsd:element>
													</xsd:sequence>

													<!-- Atributo de músico-->
													<xsd:attribute name="caracteristica" type="tipoCaracteristicaMusico"/>

												</xsd:complexType>
											</xsd:element>
										

											<!-- Opción podcaster-->
											<xsd:element name="podcaster">
												<xsd:complexType>
													<xsd:sequence>
														<!-- Elemento de podcaster-->
														<xsd:element name="podcast" maxOccurs="unbounded">
															<xsd:complexType>
																<!-- Elementos de podcast-->
																<xsd:sequence>
																	<xsd:element name="nombre" type="tipoPalabras"/>
																	<xsd:element name="duracion" type="xsd:time"/>
																	<xsd:element name="archivo" type="tipoPalabras"/>
																	<xsd:element name="NReproducciones" type="xsd:integer"/>
																	<xsd:element name="NColaboradores" type="xsd:integer"/>
																</xsd:sequence>

																<!-- Atributo podcast-->
																<xsd:attribute name="id" type="tipoIdAudio"	/>

															</xsd:complexType>
														</xsd:element>
													</xsd:sequence>

													<!-- Atributo podcaster-->


												</xsd:complexType>
													
											</xsd:element>	

										</xsd:choice>

									</xsd:sequence>

									<!-- Atributo de artista-->
								<xsd:attribute name="id" type="tipoIdArtista"/>

								</xsd:complexType>	
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="clientes">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="cliente" minOccurs="1" maxOccurs="unbounded">
								<xsd:complexType>

									<xsd:sequence>
										<!-- Elementos de cliente-->
										<xsd:element name="nombre" type="tipoPalabras"/>
										<xsd:element name="apellido" type="tipoPalabras"/>
										<xsd:element name="usuario" type="tipoPalabras"/>
										<xsd:element name="contrasena" type="tipoPalabras"/>
										<xsd:element name="fechaNacimiento" type="xsd:date"/>
										<xsd:element name="fechaRegistro" type="xsd:date"/>

										
										<xsd:element name="premium" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<!-- Elemento premium-->
													<xsd:element name="fechaCaducidad" type="xsd:date"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element> 
									</xsd:sequence>

									<!-- Atributo cliente-->
								<xsd:attribute name="id" type="tipoIdCliente"/>

								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

			</xsd:sequence>

		</xsd:complexType>
	</xsd:element>

	<!-- Types de todos los elementos (que lo necesiten)-->
	<xsd:simpleType name="tipoDescripcion">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="español"/>
			<xsd:enumeration value="frances"/>
			<xsd:enumeration value="ingles"/>
			<xsd:enumeration value="euskera"/>
			<xsd:enumeration value="aleman"/>
			<xsd:enumeration value="catalan"/>
			<xsd:enumeration value="irlandes"/>
			<xsd:enumeration value="arabe"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tipoPalabras">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\-\s/.,\(\)¿?]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- Types de los atributos-->

	 <xsd:simpleType name="tipoIdAudio">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="AU[0-9]{3}"/>
		</xsd:restriction>
	 </xsd:simpleType>

	 <xsd:simpleType name="tipoIdAlbum">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="ALB[0-9]{2}"/>
		</xsd:restriction>
	 </xsd:simpleType>

	 <xsd:simpleType name="tipoCaracteristicaMusico">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Grupo"/>
			<xsd:enumeration value="Solista"/>
		</xsd:restriction>
	 </xsd:simpleType>

	 <xsd:simpleType name="tipoIdArtista">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="A[0-9]{4}"/>
		</xsd:restriction>
	 </xsd:simpleType>

	 <xsd:simpleType name="tipoIdCliente">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="CL[0-9]{3}"/>
		</xsd:restriction>
	 </xsd:simpleType>

</xsd:schema>

=== EstibalizGutierrez/reto3Grupo6/LENGUAJES/spotify.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="artistas.xsl"?>
<spotify xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="spotify.xsd">
    <artistas>
        <artista id="A0001">
            <nombreArtistico>Eminem</nombreArtistico>
            <genero>Rap/Hip-Hop</genero>
            <imagen>imagenes/artistas/Eminem.jpg</imagen>
            <descripcion>Eminem, conocido también como Slim Shady, es uno de los raperos más influyentes y exitosos en la historia del hip hop. 
                Destaca por su técnica excepcional, rimas complejas y una capacidad única para narrar historias crudas y personales con un estilo provocador.
                A lo largo de su carrera ha ganado múltiples premios Grammy y un Oscar, consolidándose como un ícono cultural global. 
                Su impacto no solo transformó el género, sino que rompió barreras raciales en la industria musical.</descripcion>
            
            <musico caracteristica="Solista">
                <album id="ALB01">
                    <titulo>Recovery</titulo>
                    <anno>2010-06-18</anno>
                    <genero>Rap/Hip-Hop</genero>
                    <imagen>imagenes/albumes/recovery.jpg</imagen>
                    <canciones>
						<cancion id="AU001">
                            <nombre>Space bound</nombre>
                            <duracion>00:04:47</duracion>
                            <archivo>BBDD/media/cancion/AU001.mp3</archivo>
                            <NReproducciones>343</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>

                        <cancion id="AU005">
                            <nombre>Love the way you lie</nombre>
                            <duracion>00:04:47</duracion>
                            <archivo>BBDD/media/cancion/AU005.mp3</archivo>
                            <NReproducciones>203</NReproducciones>
                            <artistasInvitados>x</artistasInvitados>
                        </cancion>

                        <cancion id="AU006">
                            <nombre>No love</nombre>
                            <duracion>00:04:47</duracion>
                            <archivo>BBDD/media/cancion/AU006.mp3</archivo>
                            <NReproducciones>43493</NReproducciones>
                            <artistasInvitados>x</artistasInvitados>
                        </cancion>

                        <cancion id="AU007">
                            <nombre>Going through changes</nombre>
                            <duracion>00:04:47</duracion>
                            <archivo>BBDD/media/cancion/AU007.mp3</archivo>
                            <NReproducciones>4504</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>

                        <cancion id="AU008">
                            <nombre>Wont back down</nombre>
                            <duracion>00:04:47</duracion>
                            <archivo>BBDD/media/cancion/AU008.mp3</archivo>
                            <NReproducciones>433</NReproducciones>
                            <artistasInvitados>x</artistasInvitados>
                        </cancion>
                    </canciones>
                </album>

                <album id="ALB05">
                    <titulo>Marshall Mathers LP</titulo>
                    <anno>2020-05-23</anno>
                    <genero>Rap/hip-hop</genero>
                    <imagen>imagenes/albumes/MarshallMathersLP.jpg</imagen>
                    <canciones>
                        <cancion id="AU009">
                            <nombre>Kill you</nombre>
                            <duracion>00:04:24</duracion>
                            <archivo>media/cancion/AU009.mp3</archivo>
                            <NReproducciones>53454</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>
                        
                        <cancion id="AU010">
                            <nombre>Stan</nombre>
                            <duracion>00:06:44</duracion>
                            <archivo>media/cancion/AU010.mp3</archivo>
                            <NReproducciones>449549</NReproducciones>
                            <artistasInvitados>x</artistasInvitados>
                        </cancion>

                        <cancion id="AU011">
                            <nombre>The real slim shady</nombre>
                            <duracion>00:04:47</duracion>
                            <archivo>media/cancion/AU011.mp3</archivo>
                            <NReproducciones>4544</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>

                        <cancion id="AU012">
                            <nombre>Marshall Mathers</nombre>
                            <duracion>00:05:20</duracion>
                            <archivo>media/cancion/AU012.mp3</archivo>
                            <NReproducciones>45545</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>

                        <cancion id="AU013">
                            <nombre>Drug ballad</nombre>
                            <duracion>00:05:00</duracion>
                            <archivo>media/cancion/AU013.mp3</archivo>
                            <NReproducciones>69699</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>
                    </canciones>
                </album>
                
                <album id="ALB05">
                    <titulo>Music to be Murdered By</titulo>
                    <anno>2020-01-17</anno>
                    <genero>Rap/hip-hop</genero>
                    <imagen>imagenes/albumes/MusicToBeMurderedBy.png</imagen>
                    <canciones>
                        <cancion id="AU014">
                            <nombre>You Gon learn</nombre>
                            <duracion>00:03:54</duracion>
                            <archivo>media/cancion/AU014.mp3</archivo>
                            <NReproducciones>343</NReproducciones>
                            <artistasInvitados>x</artistasInvitados>
                        </cancion>
                        
                        <cancion id="AU015">
                            <nombre>Darkness</nombre>
                            <duracion>00:05:37</duracion>
                            <archivo>media/cancion/AU015.mp3</archivo>
                            <NReproducciones>43435</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>

                        <cancion id="AU016">
                            <nombre>Leaving heaven</nombre>
                            <duracion>00:04:25</duracion>
                            <archivo>media/cancion/AU016.mp3</archivo>
                            <NReproducciones>234</NReproducciones>
                            <artistasInvitados>x</artistasInvitados>
                        </cancion>

                        <cancion id="AU017">
                            <nombre>Never love again</nombre>
                            <duracion>00:03:00</duracion>
                            <archivo>media/cancion/AU017.mp3</archivo>
                            <NReproducciones>23</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>

                        <cancion id="AU018">
                            <nombre>No regrets</nombre>
                            <duracion>00:03:20</duracion>
                            <archivo>media/cancion/AU018.mp3</archivo>
                            <NReproducciones>656</NReproducciones>
                            <artistasInvitados>x</artistasInvitados>
                        </cancion>
                    </canciones>
                </album>
            </musico>
        </artista>
        
        <artista id="A0002">
            <nombreArtistico>BTS</nombreArtistico>
            <genero>k-pop</genero>
            <imagen>imagenes/artistas/bts.jpg</imagen>
            <descripcion>Septeto surcoreano formado en Seúl en 2010. Es el grupo de K-pop más influyente a nivel mundial, compuesto por Jin, Suga, J-Hope, RM, Jimin, V y Jungkook. 
                Han encabezado las listas de Billboard y son reconocidos por su impacto cultural global y récords en ventas.</descripcion>
        
            <musico caracteristica="Grupo">
                <album id="ALB06">
                    <titulo>Love Yourself Answer</titulo>
                    <anno>2017-08-24</anno>
                    <genero>k-pop</genero>
                    <imagen>imagenes/albumes/LoveYourselfAnswer.jpg</imagen>
                    <canciones>
                        <cancion id="AU019">
                            <nombre>DNA</nombre>
                            <duracion>00:03:43</duracion>
                            <archivo>BBDD/media/cancion/AU019.mp3</archivo>
                            <NReproducciones>43535</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>

                        <cancion id="AU020">
                            <nombre>Fake love</nombre>
                            <duracion>00:04:02</duracion>
                            <archivo>media/cancion/AU020.mp3</archivo>
                            <NReproducciones>656</NReproducciones>
                            <artistasInvitados>ninguno</artistasInvitados>
                        </cancion>
